flake8_checks:
    image: debian:stable
    script:
    - apt-get update -q
    - apt-get install -qy python3-flake8
    - python3 -m flake8 emtools/


pydocstyle_checks:
    image: debian:stable
    script:
    - apt-get update -q
    - apt-get install -qy python3-pip
    - pip3 install pydocstyle
    - python3 -m pydocstyle emtools/
    allow_failure: true

